### ISSUE TITLE
Price request for 2 A.M. missing

### ISSUE THREAD

**Issue by Negropo** [flod-1/LoxBerry-Plugin-Tibber2MQTT#3]
Using v2.5.0 on LB3.0.0.2 theres is no MQTT transmission for tibber_absprices_today_2_total or level. This data field is totaly missing.

![snip_20230326122956](https://user-images.githubusercontent.com/29814961/227769926-5a4c1c28-864c-4cf2-bef4-80037e8a99da.png)

**Comment by flod-1** [comment]
Hello @Negropo,

- is this the value always missing or just sometimes?
- is this value missing for today only or also for tomorrow?

Can you please provide the file opt/loxberry/data/plugins/tibber2mqtt/pricecache.json to me?
You can download it through file manager in loxberry.

**Comment by Negropo** [comment]
Hello @flod-1,
the value was missing sometimes and only for today values as far as I could saw.
[pricecache.zip](https://github.com/flod-1/LoxBerry-Plugin-Tibber2MQTT/files/11119455/pricecache.zip)

**Comment by flod-1** [comment]
@Negropo thanks! 
Do you have multiple homes in Tibber App?

**Comment by Negropo** [comment]
No, I only have one home in my Tibber App.

**Comment by flod-1** [comment]
@Negropo Unfortunately I'm not able to reproduce this issue based on the data you have in pricing cache. Also when double-checking code, there's no situation whre no. 2 can be skipped. It's just looping and incrementing at all relevant stages. And as 3, etc. is there, code should have also passed no. 2.

Are you sure that the value is missing at all and it's not just shown somewhere else? 
Sometimes sorting is not 100% (at least for me in the past). 

This would be the next steps, if it's really a missing value:

1. If it is only missing sometimes, it should still be visible in Incoming overview with an old date. Can you please see if it is like this? It's shown for 24 hours there, showing the last transmission date.
2. If it's not there, please go to menue "MQTT Finder" instead of "Incoming overview". There also older ones are listed. Is it visible there? What are the timestamps there?

**Comment by flod-1** [comment]
Closed as not reproducable and no response.
